[package]
name = "webring"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
serde = {version = "1.0.219", features=["derive"]}
tiny_http = "0.12.0"
toml = "0.9.5"
