port = 8080
ip_addr = "127.0.0.1"
title = "Commutative Webring"

[members.connorduncan]
title = "Connor's Blog"
author = "Connor Duncan"
url = "https://www.connorduncan.xyz/blog"

[members.quajzen]
title = "Quajzen"
author = "Quajzen"
url = "https://quajzen.page"
